version: 1.0.{build}
init:
- cmd: 
before_build:
- cmd: >-
    mkdir cmake-build

    cd cmake-build

    cmake -G"Visual Studio 14 2015 Win64" ..

    cd ..
build:
  parallel: true
  verbosity: minimal
